# Generated by Django 5.0.6 on 2024-05-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('units', models.IntegerField()),
                ('total', models.FloatField(null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugawan.branch')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugawan.product')),
            ],
        ),
    ]
