# Generated by Django 5.0.6 on 2024-05-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugawan.branch'),
        ),
    ]
