# Generated by Django 5.0.6 on 2024-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0007_alter_transaction_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='halin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=150)),
                ('transdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.CharField(max_length=150)),
                ('price', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
            ],
        ),
    ]
