# Generated by Django 5.0.6 on 2024-05-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0008_halin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halin',
            name='total',
        ),
    ]
