# Generated by Django 5.0.6 on 2024-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0010_expense_alter_halin_transdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.CharField(choices=[('WATER', 'water'), ('ICE', 'ice'), ('GAS', 'gas'), ('ELECTRICITY', 'electricity'), ('RENT', 'rent'), ('INGREDIENTS', 'ingredients'), ('OTHERS', 'others')], default='WATER', max_length=150),
        ),
    ]
