# Generated by Django 5.0.6 on 2024-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0012_alter_expense_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('STOCKS', 'Stocks'), ('OPERATING', 'Operating')], default='Consumable', max_length=150),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.CharField(choices=[('EGG', 'Egg'), ('WATER', 'Water'), ('ICE', 'Ice'), ('OIL', 'Oil'), ('GAS', 'Gas'), ('ELECTRICITY', 'Electricity'), ('RENT', 'Rent'), ('INGREDIENTS', 'Ingredients'), ('SOFTDRINKS', 'Softdrinks'), ('SALARY', 'Softdrinks'), ('OTHERS', 'Others')], default='WATER', max_length=150),
        ),
    ]
