# Generated by Django 5.0.6 on 2024-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0014_alter_expense_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Qty',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
