# Generated by Django 5.0.6 on 2024-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugawan', '0015_expense_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Qty',
            field=models.IntegerField(null=True),
        ),
    ]
